#!/usr/bin/env python3
"""Generate the small fixed Scala ALU vector set from pinned scalar CMSIS-NN."""
import argparse
import ctypes
import json
from pathlib import Path
import subprocess
import sys
import tempfile


CASES = [
    (1, 1 << 30, -1), (-1, 1 << 30, -1),
    (3, 1 << 30, -1), (-3, 1 << 30, -1),
    (5, 1 << 30, -2), (-5, 1 << 30, -2),
    (7, 1 << 30, -2), (-7, 1 << 30, -2),
    (123456789, 1879048193, -3), (-123456789, 1879048193, -3),
    (1073741823, 2147483647, -7), (-1073741824, 2147483647, -7),
    (-2147483648, 2147483647, -31), (2147483647, 2147483647, -31),
    (-1, 2147483647, -31), (1, 2147483647, -31),
]


def main():
    repo_root = Path(__file__).resolve().parents[4]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=repo_root / "vta/hardware/chisel/src/test/resources/cmsis_requantize_golden.csv",
    )
    args = parser.parse_args()
    cmsis_root = Path(__file__).with_name("cmsis-nn")
    build_script = Path(__file__).with_name("build_reference.py")
    with tempfile.TemporaryDirectory(prefix="vta-cmsis-golden-") as temp:
        subprocess.run(
            [sys.executable, str(build_script), "--cmsis-root", str(cmsis_root),
             "--output-dir", temp],
            check=True, capture_output=True, text=True,
        )
        manifest = json.loads((Path(temp) / "manifest.json").read_text(encoding="utf-8"))
        expected_macros = {
            "double": [],
            "single": ["CMSIS_NN_USE_SINGLE_ROUNDING"],
        }
        if manifest["tag"] != "v8.0.0" or manifest["build_macros"] != expected_macros:
            raise RuntimeError("unexpected CMSIS-NN golden-vector build configuration")
        requantizers = {}
        for mode in ("double", "single"):
            library = ctypes.CDLL(str(Path(temp) / manifest["libraries"][mode]))
            requantize = library.cmsis_requantize
            requantize.argtypes = [ctypes.c_int32, ctypes.c_int32, ctypes.c_int32]
            requantize.restype = ctypes.c_int32
            requantizers[mode] = requantize
        rows = [
            "# CMSIS-NN v8.0.0 pinned scalar arm_nn_requantize in both build modes",
            "# Generated by vta/tests/qconv2d/reference/generate_chisel_golden.py",
            "x,multiplier,shift,double_result,single_result",
        ]
        rows.extend(
            f"{x},{multiplier},{shift},{requantizers['double'](x, multiplier, shift)},"
            f"{requantizers['single'](x, multiplier, shift)}"
            for x, multiplier, shift in CASES
        )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(rows) + "\n", encoding="ascii")
    print(f"{args.output}: {len(CASES)} CMSIS-NN v8.0.0 vectors")


if __name__ == "__main__":
    main()
